export const LOCAL_GUIDE_CARDS = [
  {
    id: 'autumn-winter',
    badge: 'Autumn & Winter Guide',
    text: 'Cosy indoor culture, crisp walks and festive pop-ups — the best of London in the colder months, from King’s Cross.',
    image: '/img/basic/local-guide-card-autumn.webp',
    imageAlt: 'Autumn along the Thames — bench, leaves and London skyline',
    href: '/blogs-en/london-autumn-winter-kings-cross-st-pancras',
  },
  {
    id: 'spring-summer',
    badge: 'Spring & Summer Guide',
    text: 'Discover the best things to do in London in spring and summer 2026.',
    image: '/img/basic/local-guide-card-spring.webp',
    imageAlt: 'London in spring — parks and city views',
    href: '/blogs-en/things-to-do-london-spring-summer-2026',
  },
  {
    id: 'local-discounts',
    badge: 'Local Discounts',
    text: "Explore King's Cross and enjoy exclusive local discounts as our guest.",
    image: '/img/basic/local-guide-card-discounts.webp',
    imageAlt: 'Outdoor dining near King’s Cross',
    href: 'https://kayagnhlondon.com/local-discounts/',
    external: true,
  },
  {
    id: 'discover-hotel',
    badge: 'Discover Kaya Great Northern Hotel',
    text: 'Let us take care of your visit with the quirks and perks of a boutique luxury experience in a Victorian railway hotel.',
    textEmphasis: ['boutique luxury'],
    image: '/img/basic/local-guide-card-hotel.webp',
    imageAlt: 'Pantry at Kaya Great Northern Hotel',
    href: 'https://kayagnhlondon.com/things-to-do/whats-on-great-northern-hotel',
    external: true,
  },
  {
    id: 'london-favourites',
    badge: 'London Favourites',
    text: 'Take a look at our top 5 must-visits for London. Plan your perfect visit and discover journey times from our door.',
    textEmphasis: ['top 5', 'discover journey times'],
    image: '/img/basic/local-guide-card-favourites.webp',
    imageAlt: 'Tower of London',
    href: 'https://kayagnhlondon.com/things-to-do/must-see-london/',
    external: true,
  },
  {
    id: 'kings-cross',
    badge: "King's Cross",
    text: 'Our list of local favourites make your trip all the more colourful, and the memories richer.',
    textEmphasis: ['local favourites'],
    image: '/img/basic/local-guide-card-kings-cross.webp',
    imageAlt: "King's Cross — Coal Drops Yard and neighbourhood",
    href: 'https://kayagnhlondon.com/local-guide/kings-cross/',
    external: true,
  },
  {
    id: 'why-camden',
    badge: 'Why visit Camden',
    text: 'Home to dazzling markets, quaint canals and vibrant scenery — a must-visit whatever the weather!',
    image: '/img/basic/local-guide-card-camden.webp',
    imageAlt: 'Colourful umbrellas at Camden Market',
    href: 'https://kayagnhlondon.com/things-to-do/why-visit-camden/',
    external: true,
  },
];
